from typing import Any

def html_attribute(attribute_name: str, default: Any = ...) -> property: ...
def boolean_html_attribute(attribute_name: str) -> property: ...
def int_html_attribute(attribute_name: str, default: Any = ...) -> property: ...
def float_html_attribute(attribute_name: str, default: Any = ...) -> property: ...
def time_html_attribute(attribute_name: str, default: Any = ...) -> property: ...
def list_html_attribute(attribute_name: str) -> property: ...
def data_attribute(data_name: str, default: Any = ...) -> property: ...
def css_class_attribute(css_class: str) -> property: ...
